name: Tests Run
on:
  workflow_dispatch:

jobs:
  proefme:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6.0.0
      
      - name: Create build zip
        run: |
          mkdir -p build
          zip -r build/app.zip . \
            -x "*.git*" ".github/*" "build/*"

      - run: npm install                       # install packages
      - run: npm test -- --coverage                     # run tests (configured to use jest-junit reporter)
      - uses: mridang/action-test-reporter@v1.3.0
      
  
