name: Tests Run
on:
  workflow_dispatch:

jobs:
  proefme:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6.0.0
      
      - name: Create build zip
        run: |
          mkdir -p build
          zip -r build/app.zip . \
            -x "*.git*" ".github/*" "build/*"

      - run: npm ci                       # install packages
      - run: npm test                     # run tests (configured to use jest-junit reporter)
      - uses: actions/upload-artifact@v4  # upload test results
        if: ${{ !cancelled() }}           # run this step even if previous step failed
        with:
          name: test-results
          path: jest-junit.xml
  
